//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JackTheVideoRipper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Executables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Executables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JackTheVideoRipper.Properties.Executables", typeof(Executables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aria2c.exe.
        /// </summary>
        internal static string Aria2c {
            get {
                return ResourceManager.GetString("Aria2c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AtomicParsley.exe.
        /// </summary>
        internal static string AtomicParsley {
            get {
                return ResourceManager.GetString("AtomicParsley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmd.exe.
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exiftool.exe.
        /// </summary>
        internal static string ExifTool {
            get {
                return ResourceManager.GetString("ExifTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explorer.exe.
        /// </summary>
        internal static string Explorer {
            get {
                return ResourceManager.GetString("Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ffmpeg.exe.
        /// </summary>
        internal static string FFMPEG {
            get {
                return ResourceManager.GetString("FFMPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ffprobe.exe.
        /// </summary>
        internal static string FFProbe {
            get {
                return ResourceManager.GetString("FFProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to handbrake.exe.
        /// </summary>
        internal static string Handbrake {
            get {
                return ResourceManager.GetString("Handbrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taskmgr.exe.
        /// </summary>
        internal static string TaskManager {
            get {
                return ResourceManager.GetString("TaskManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vlc.exe.
        /// </summary>
        internal static string VLC {
            get {
                return ResourceManager.GetString("VLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yt-dlp.exe.
        /// </summary>
        internal static string YouTubeDL {
            get {
                return ResourceManager.GetString("YouTubeDL", resourceCulture);
            }
        }
    }
}
