//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JackTheVideoRipper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JackTheVideoRipper.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item has already been downloaded, continue?.
        /// </summary>
        internal static string AlreadyDownloaded {
            get {
                return ResourceManager.GetString("AlreadyDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application already running!.
        /// </summary>
        internal static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard content is not valid url!.
        /// </summary>
        internal static string ClipboardInvalidUrl {
            get {
                return ResourceManager.GetString("ClipboardInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command copied to clipboard!.
        /// </summary>
        internal static string CommandCopied {
            get {
                return ResourceManager.GetString("CommandCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command failed to execute! (Exit Code = {0}).
        /// </summary>
        internal static string CommandFailed {
            get {
                return ResourceManager.GetString("CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing.
        /// </summary>
        internal static string Compressing {
            get {
                return ResourceManager.GetString("Compressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context action failed!.
        /// </summary>
        internal static string ContextActionFailed {
            get {
                return ResourceManager.GetString("ContextActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counters successfully initialized.
        /// </summary>
        internal static string CountersInitialized {
            get {
                return ResourceManager.GetString("CountersInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find {0} on your system... Some functions may not be available or proceed correctly. Please reinstall this app..
        /// </summary>
        internal static string DependencyMissing {
            get {
                return ResourceManager.GetString("DependencyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} does not exist!.
        /// </summary>
        internal static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- press ENTER --.
        /// </summary>
        internal static string ExifToolPressEnter {
            get {
                return ResourceManager.GetString("ExifToolPressEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have pending operations, are you sure you want to exit?.
        /// </summary>
        internal static string ExitWarning {
            get {
                return ResourceManager.GetString("ExitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse provided url!.
        /// </summary>
        internal static string FailedParseUrl {
            get {
                return ResourceManager.GetString("FailedParseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download {0}.
        /// </summary>
        internal static string FailedToDownload {
            get {
                return ResourceManager.GetString("FailedToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists. Overwrite? [y/N].
        /// </summary>
        internal static string FFMPEGFileExists {
            get {
                return ResourceManager.GetString("FFMPEGFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} finished downloading!.
        /// </summary>
        internal static string FinishedDownloading {
            get {
                return ResourceManager.GetString("FinishedDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required components not installed! This app will NOT behave correctly because its critical dependencies are missing..
        /// </summary>
        internal static string InstallationError {
            get {
                return ResourceManager.GetString("InstallationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components have been installed successfully!.
        /// </summary>
        internal static string InstallationSuccess {
            get {
                return ResourceManager.GetString("InstallationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yt-dlp is required and is not bundled with the installer as it is updated frequently. Install?.
        /// </summary>
        internal static string InstallMessage {
            get {
                return ResourceManager.GetString("InstallMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only embed thumbnails in mp3 and m4a containers!.
        /// </summary>
        internal static string InvalidAudio {
            get {
                return ResourceManager.GetString("InvalidAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid url provided to create command from.
        /// </summary>
        internal static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL detected, skipping: {0}.
        /// </summary>
        internal static string InvalidUrlBulk {
            get {
                return ResourceManager.GetString("InvalidUrlBulk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot embed thumbnails in non-mp4 containers!.
        /// </summary>
        internal static string InvalidVideo {
            get {
                return ResourceManager.GetString("InvalidVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link from domain {0} is not supported. Please see About page for a list of supported services..
        /// </summary>
        internal static string LinkNotSupported {
            get {
                return ResourceManager.GetString("LinkNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client has lost connection to internet!.
        /// </summary>
        internal static string LostConnection {
            get {
                return ResourceManager.GetString("LostConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve metadata!.
        /// </summary>
        internal static string MetadataLookupFailed {
            get {
                return ResourceManager.GetString("MetadataLookupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version of {0} {1} Available! View Download Page?.
        /// </summary>
        internal static string NewUpdate {
            get {
                return ResourceManager.GetString("NewUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no audio metadata could be extracted).
        /// </summary>
        internal static string NoAudioMetadata {
            get {
                return ResourceManager.GetString("NoAudioMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no video metadata could be extracted).
        /// </summary>
        internal static string NoVideoMetadata {
            get {
                return ResourceManager.GetString("NoVideoMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like this file already exists, overwrite it?.
        /// </summary>
        internal static string OverwriteFile {
            get {
                return ResourceManager.GetString("OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed.
        /// </summary>
        internal static string ProcessCompleted {
            get {
                return ResourceManager.GetString("ProcessCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process initialized.
        /// </summary>
        internal static string ProcessInitialized {
            get {
                return ResourceManager.GetString("ProcessInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process started execution.
        /// </summary>
        internal static string ProcessStarted {
            get {
                return ResourceManager.GetString("ProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirected from video proxy site {0} to {1}.
        /// </summary>
        internal static string RedirectedProxy {
            get {
                return ResourceManager.GetString("RedirectedProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource could not be found at: {0} (Error {1}).
        /// </summary>
        internal static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Info.
        /// </summary>
        internal static string Retrieving {
            get {
                return ResourceManager.GetString("Retrieving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Metadata.
        /// </summary>
        internal static string SavingMetadata {
            get {
                return ResourceManager.GetString("SavingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Startup Tasks.
        /// </summary>
        internal static string StartupTasks {
            get {
                return ResourceManager.GetString("StartupTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASK CANCELLED (REASON: TIMEOUT EXPIRED).
        /// </summary>
        internal static string TaskCancelled {
            get {
                return ResourceManager.GetString("TaskCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcoding.
        /// </summary>
        internal static string Transcoding {
            get {
                return ResourceManager.GetString("Transcoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application closed due to unhandled exception..
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App is currently up to date!.
        /// </summary>
        internal static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors detected while verifying file {0} (full report: {0}).
        /// </summary>
        internal static string VerifyErrorsDetected {
            get {
                return ResourceManager.GetString("VerifyErrorsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying file: {0}.
        /// </summary>
        internal static string VerifyingFile {
            get {
                return ResourceManager.GetString("VerifyingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors detected in file {0}..
        /// </summary>
        internal static string VerifyNoErrors {
            get {
                return ResourceManager.GetString("VerifyNoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has already been downloaded.
        /// </summary>
        internal static string YouTubeDLAlreadyDownloaded {
            get {
                return ResourceManager.GetString("YouTubeDLAlreadyDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency yt-dlp has been upgraded from {0} to {1}!.
        /// </summary>
        internal static string YouTubeDLUpdated {
            get {
                return ResourceManager.GetString("YouTubeDLUpdated", resourceCulture);
            }
        }
    }
}
