//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JackTheVideoRipper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JackTheVideoRipper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find AtomicParsley on your system.. This app will NOT behave correctly because its critical dependencies are missing. Please reinstall this app..
        /// </summary>
        internal static string AtomicParsleyMissing {
            get {
                return ResourceManager.GetString("AtomicParsleyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have pending downloads, are you sure you want to exit?.
        /// </summary>
        internal static string ExitWarning {
            get {
                return ResourceManager.GetString("ExitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find FFmpeg on your system. This app will NOT behave correctly because its critical dependencies are missing. Please reinstall this app..
        /// </summary>
        internal static string FfmpegMissing {
            get {
                return ResourceManager.GetString("FfmpegMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required components not installed! This app will NOT behave correctly because its critical dependencies are missing.&quot;.
        /// </summary>
        internal static string InstallationError {
            get {
                return ResourceManager.GetString("InstallationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components have been installed successfully!.
        /// </summary>
        internal static string InstallationSuccess {
            get {
                return ResourceManager.GetString("InstallationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yt-dlp is required and is not bundled with the installer as it is updated frequently. Install?.
        /// </summary>
        internal static string InstallMessage {
            get {
                return ResourceManager.GetString("InstallMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only embed thumbnails in mp3 and m4a containers!.
        /// </summary>
        internal static string InvalidAudio {
            get {
                return ResourceManager.GetString("InvalidAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot embed thumbnails in non-mp4 containers!.
        /// </summary>
        internal static string InvalidVideo {
            get {
                return ResourceManager.GetString("InvalidVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version JackTheVideoRipper {0} Available! View Download Page?.
        /// </summary>
        internal static string NewUpdate {
            get {
                return ResourceManager.GetString("NewUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App is currently up to date!.
        /// </summary>
        internal static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency yt-dlp has been upgraded from {0} to {1}!.
        /// </summary>
        internal static string YouTubeDLUpdated {
            get {
                return ResourceManager.GetString("YouTubeDLUpdated", resourceCulture);
            }
        }
    }
}
