//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JackTheVideoRipper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RFileSystem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RFileSystem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JackTheVideoRipper.Properties.RFileSystem", typeof(RFileSystem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find file to open at {0}.
        /// </summary>
        internal static string CouldNotOpenFile {
            get {
                return ResourceManager.GetString("CouldNotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start File Explorer!.
        /// </summary>
        internal static string CouldNotStartExplorer {
            get {
                return ResourceManager.GetString("CouldNotStartExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start process: {0}.
        /// </summary>
        internal static string CouldNotStartProcess {
            get {
                return ResourceManager.GetString("CouldNotStartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start Task Manager!.
        /// </summary>
        internal static string CouldNotStartTaskManager {
            get {
                return ResourceManager.GetString("CouldNotStartTaskManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create process with empty bin path!.
        /// </summary>
        internal static string EmptyBinPath {
            get {
                return ResourceManager.GetString("EmptyBinPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explorer.exe.
        /// </summary>
        internal static string Exe_Explorer {
            get {
                return ResourceManager.GetString("Exe_Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taskmgr.exe.
        /// </summary>
        internal static string Exe_TaskManager {
            get {
                return ResourceManager.GetString("Exe_TaskManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: File Already Exists.
        /// </summary>
        internal static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Process already running!.
        /// </summary>
        internal static string ProcessAlreadyRunning {
            get {
                return ResourceManager.GetString("ProcessAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Win32_Process WHERE ParentProcessID={0}.
        /// </summary>
        internal static string SelectProcessById {
            get {
                return ResourceManager.GetString("SelectProcessById", resourceCulture);
            }
        }
    }
}
