//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JackTheVideoRipper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Urls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Urls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JackTheVideoRipper.Properties.Urls", typeof(Urls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/dantheman213/JackTheVideoRipper/releases.
        /// </summary>
        internal static string ApplicationUpdate {
            get {
                return ResourceManager.GetString("ApplicationUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/aria2/aria2/releases/latest.
        /// </summary>
        internal static string Aria2c {
            get {
                return ResourceManager.GetString("Aria2c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://atomicparsley.sourceforge.net.
        /// </summary>
        internal static string AtomicParsley {
            get {
                return ResourceManager.GetString("AtomicParsley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sourceforge.net/projects/exiftool/files/latest/download.
        /// </summary>
        internal static string ExifTool {
            get {
                return ResourceManager.GetString("ExifTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.ffmpeg.org/download.html.
        /// </summary>
        internal static string FFMPEG {
            get {
                return ResourceManager.GetString("FFMPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://handbrake.fr/.
        /// </summary>
        internal static string Handbrake {
            get {
                return ResourceManager.GetString("Handbrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://handbrake.fr/downloads.php.
        /// </summary>
        internal static string HandbrakeDownload {
            get {
                return ResourceManager.GetString("HandbrakeDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/dantheman213/JackTheVideoRipper/master/version.
        /// </summary>
        internal static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.videolan.org/vlc.
        /// </summary>
        internal static string VLC {
            get {
                return ResourceManager.GetString("VLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.microsoft.com/en-us/download/details.aspx?id=26999.
        /// </summary>
        internal static string VS2010Redistributables {
            get {
                return ResourceManager.GetString("VS2010Redistributables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/yt-dlp/yt-dlp.
        /// </summary>
        internal static string YouTubeDL {
            get {
                return ResourceManager.GetString("YouTubeDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe.
        /// </summary>
        internal static string YouTubeDLDownload {
            get {
                return ResourceManager.GetString("YouTubeDLDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/watch?v={0}.
        /// </summary>
        internal static string YouTubeVideo {
            get {
                return ResourceManager.GetString("YouTubeVideo", resourceCulture);
            }
        }
    }
}
